### ISSUE TITLE
Fix the New Ticket GUI currently the year seems to be hard coded to 2018.

### ISSUE THREAD

**Issue by darknite12** [darknite12/rms#46]

**Comment by Link1393** [comment]
The problem in this issue is not that the year is hard coded. The problem is that the ticket GUI is trying to get the prices for the tickets in the current year. And this ones are not in the DB yet.
We need to decide if we should make a GUI to initialise the year.

**Comment by darknite12** [comment]
> The problem in this issue is not that the year is hard coded. The problem is that the ticket GUI is trying to get the prices for the tickets in the current year. And this ones are not in the DB yet.

But why? tickets have no association to a year, they do have an association to an event, and an association to ticket_price and it is that ticket_price association that gives the ticket the price. I think that we might have decided to implicitly link a ticket to a year through the means of the year field in ticket price? Is that what is happening?

I have some ideas. Lets talk over the phone one day. But i will write them down
* We need to create the New Event GUI #45 
* In the New ticket UI, we need to allow to go into that page without the need of a year BUT we cannot allow for a creation of a ticket without an event and without at ticket_price. This would be similar to the New Sitting Table GUI, we can go into the New Sitting Table GUI and associate an event.
* To make things clear we may need to add an association between event and ticket_price and by default that would be the price a ticket associated to an event will have. In this way,  when we create a ticket we only need to associate it to the event and by default the ticket will get the associated price to that event. If we need to change the ticket price for whatever reason we can.
* we should have a way to mark an event **completed** so that no one could add tickets/sitting tables to this event (ie. no one should be able to add tickets to last year's fundraising dinner
